//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Dodoe.Bindings {

public class DodoeVec3 : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DodoeVec3(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DodoeVec3 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(DodoeVec3 obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~DodoeVec3() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          DodoeRuntimePINVOKE.delete_DodoeVec3(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public float x {
    set {
      DodoeRuntimePINVOKE.DodoeVec3_x_set(swigCPtr, value);
    } 
    get {
      float ret = DodoeRuntimePINVOKE.DodoeVec3_x_get(swigCPtr);
      return ret;
    } 
  }

  public float y {
    set {
      DodoeRuntimePINVOKE.DodoeVec3_y_set(swigCPtr, value);
    } 
    get {
      float ret = DodoeRuntimePINVOKE.DodoeVec3_y_get(swigCPtr);
      return ret;
    } 
  }

  public float z {
    set {
      DodoeRuntimePINVOKE.DodoeVec3_z_set(swigCPtr, value);
    } 
    get {
      float ret = DodoeRuntimePINVOKE.DodoeVec3_z_get(swigCPtr);
      return ret;
    } 
  }

  public DodoeVec3() : this(DodoeRuntimePINVOKE.new_DodoeVec3(), true) {
  }

}

}
