//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Dodoe.Bindings {

public class DodoeColor : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DodoeColor(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DodoeColor obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(DodoeColor obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~DodoeColor() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          DodoeRuntimePINVOKE.delete_DodoeColor(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public float r {
    set {
      DodoeRuntimePINVOKE.DodoeColor_r_set(swigCPtr, value);
    } 
    get {
      float ret = DodoeRuntimePINVOKE.DodoeColor_r_get(swigCPtr);
      return ret;
    } 
  }

  public float g {
    set {
      DodoeRuntimePINVOKE.DodoeColor_g_set(swigCPtr, value);
    } 
    get {
      float ret = DodoeRuntimePINVOKE.DodoeColor_g_get(swigCPtr);
      return ret;
    } 
  }

  public float b {
    set {
      DodoeRuntimePINVOKE.DodoeColor_b_set(swigCPtr, value);
    } 
    get {
      float ret = DodoeRuntimePINVOKE.DodoeColor_b_get(swigCPtr);
      return ret;
    } 
  }

  public float a {
    set {
      DodoeRuntimePINVOKE.DodoeColor_a_set(swigCPtr, value);
    } 
    get {
      float ret = DodoeRuntimePINVOKE.DodoeColor_a_get(swigCPtr);
      return ret;
    } 
  }

  public DodoeColor() : this(DodoeRuntimePINVOKE.new_DodoeColor(), true) {
  }

}

}
