// do@Redlive

#ifndef DOE_SHADER_PARAMETER_SETS_GLSL
#define DOE_SHADER_PARAMETER_SETS_GLSL

#define DOE_SET_GLOBAL       0
#define DOE_SET_VIEW         1
#define DOE_SET_PASS         2
#define DOE_SET_MATERIAL     3
#define DOE_SET_PRIMITIVE    4
#define DOE_SET_BINDLESS     5

#define DOE_GLOBAL_BINDING_CONSTANTS    0

#define DOE_VIEW_BINDING_CONSTANTS      0

#define DOE_PASS_BINDING_CONSTANTS      0
#define DOE_PASS_BINDING_INPUT0         1
#define DOE_PASS_BINDING_INPUT1         2
#define DOE_PASS_BINDING_INPUT2         3
#define DOE_PASS_BINDING_INPUT3         4
#define DOE_PASS_BINDING_INPUT4         5
#define DOE_PASS_BINDING_INPUT5         6
#define DOE_PASS_BINDING_INPUT6         7
#define DOE_PASS_BINDING_INPUT7         8
#define DOE_PASS_BINDING_SAMPLER        9

#define DOE_MATERIAL_BINDING_CONSTANTS      0
#define DOE_MATERIAL_BINDING_SAMPLER        1
#define DOE_MATERIAL_BINDING_BASE_COLOR     2
#define DOE_MATERIAL_BINDING_METALLIC_ROUGH 3
#define DOE_MATERIAL_BINDING_NORMAL         4
#define DOE_MATERIAL_BINDING_EMISSIVE       5

#define DOE_PRIMITIVE_BINDING_CONSTANTS  0

#define DOE_BINDLESS_BINDING_TEXTURES    0

#endif
