<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>12.0</LangVersion>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <OutputType>Library</OutputType>
    <AssemblyName>OnlyOne</AssemblyName>
    <OutputPath>./</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <BaseIntermediateOutputPath>./obj/</BaseIntermediateOutputPath>
    <IntermediateOutputPath>./obj/</IntermediateOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="GreenCake">
      <HintPath>../../../../engine/src/scriptcore/bin/Debug/net10.0/GreenCake.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="../Assets/Scripts/GameControllerSystem.cs" />
    <Compile Include="../Assets/Scripts/MapImportSystem.cs" />
    <Compile Include="../Assets/Scripts/MoveSpeedComponent.cs" />
    <Compile Include="../Assets/Scripts/PlayerController.cs" />
    <Compile Include="../Assets/Scripts/PrintMessageSystem.cs" />
    <Compile Include="../Assets/Scripts/TestSystem.cs" />
  </ItemGroup>

</Project>
