/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


#define SWIG_VERSION 0x040401
#define SWIGCSHARP

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif

#if defined(__cplusplus) && __cplusplus >=201103L
# define SWIG_NOEXCEPT noexcept
#else
# define SWIG_NOEXCEPT throw()
#endif 

/* -----------------------------------------------------------------------------
 * swigcompat.swg
 *
 * Macros to provide support compatibility with older C and C++ standards.
 *
 * Note that SWIG expects __cplusplus to be defined to the appropriate C++ standard.
 * MSVC users are urged to check and examine the /Zc:__cplusplus compiler option.
 * See https://learn.microsoft.com/en-us/cpp/build/reference/zc-cplusplus.
 * ----------------------------------------------------------------------------- */

/* C99 and C++11 should provide snprintf, but define SWIG_NO_SNPRINTF
 * if you're missing it.
 */
#if ((defined __STDC_VERSION__ && __STDC_VERSION__ >= 199901L) || \
     (defined __cplusplus && __cplusplus >= 201103L) || \
     defined SWIG_HAVE_SNPRINTF) && \
    !defined SWIG_NO_SNPRINTF
# define SWIG_snprintf(O,S,F,A) snprintf(O,S,F,A)
# define SWIG_snprintf2(O,S,F,A,B) snprintf(O,S,F,A,B)
#else
/* Fallback versions ignore the buffer size, but most of our uses either have a
 * fixed maximum possible size or dynamically allocate a buffer that's large
 * enough.
 */
# define SWIG_snprintf(O,S,F,A) sprintf(O,F,A)
# define SWIG_snprintf2(O,S,F,A,B) sprintf(O,F,A,B)
#endif


#include <stdlib.h>
#include <string.h>
#include <stdio.h>


/* Support for throwing C# exceptions from C/C++. There are two types: 
 * Exceptions that take a message and ArgumentExceptions that take a message and a parameter name. */
typedef enum {
  SWIG_CSharpApplicationException,
  SWIG_CSharpArithmeticException,
  SWIG_CSharpDivideByZeroException,
  SWIG_CSharpIndexOutOfRangeException,
  SWIG_CSharpInvalidCastException,
  SWIG_CSharpInvalidOperationException,
  SWIG_CSharpIOException,
  SWIG_CSharpNullReferenceException,
  SWIG_CSharpOutOfMemoryException,
  SWIG_CSharpOverflowException,
  SWIG_CSharpSystemException
} SWIG_CSharpExceptionCodes;

typedef enum {
  SWIG_CSharpArgumentException,
  SWIG_CSharpArgumentNullException,
  SWIG_CSharpArgumentOutOfRangeException
} SWIG_CSharpExceptionArgumentCodes;

typedef void (SWIGSTDCALL* SWIG_CSharpExceptionCallback_t)(const char *);
typedef void (SWIGSTDCALL* SWIG_CSharpExceptionArgumentCallback_t)(const char *, const char *);

typedef struct {
  SWIG_CSharpExceptionCodes code;
  SWIG_CSharpExceptionCallback_t callback;
} SWIG_CSharpException_t;

typedef struct {
  SWIG_CSharpExceptionArgumentCodes code;
  SWIG_CSharpExceptionArgumentCallback_t callback;
} SWIG_CSharpExceptionArgument_t;

static SWIG_CSharpException_t SWIG_csharp_exceptions[] = {
  { SWIG_CSharpApplicationException, NULL },
  { SWIG_CSharpArithmeticException, NULL },
  { SWIG_CSharpDivideByZeroException, NULL },
  { SWIG_CSharpIndexOutOfRangeException, NULL },
  { SWIG_CSharpInvalidCastException, NULL },
  { SWIG_CSharpInvalidOperationException, NULL },
  { SWIG_CSharpIOException, NULL },
  { SWIG_CSharpNullReferenceException, NULL },
  { SWIG_CSharpOutOfMemoryException, NULL },
  { SWIG_CSharpOverflowException, NULL },
  { SWIG_CSharpSystemException, NULL }
};

static SWIG_CSharpExceptionArgument_t SWIG_csharp_exceptions_argument[] = {
  { SWIG_CSharpArgumentException, NULL },
  { SWIG_CSharpArgumentNullException, NULL },
  { SWIG_CSharpArgumentOutOfRangeException, NULL }
};

static void SWIGUNUSED SWIG_CSharpSetPendingException(SWIG_CSharpExceptionCodes code, const char *msg) {
  SWIG_CSharpExceptionCallback_t callback = SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions)/sizeof(SWIG_CSharpException_t)) {
    callback = SWIG_csharp_exceptions[code].callback;
  }
  callback(msg);
}

static void SWIGUNUSED SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpExceptionArgumentCodes code, const char *msg, const char *param_name) {
  SWIG_CSharpExceptionArgumentCallback_t callback = SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions_argument)/sizeof(SWIG_CSharpExceptionArgument_t)) {
    callback = SWIG_csharp_exceptions_argument[code].callback;
  }
  callback(msg, param_name);
}


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionCallbacks_DodoeRuntime(
                                                SWIG_CSharpExceptionCallback_t applicationCallback,
                                                SWIG_CSharpExceptionCallback_t arithmeticCallback,
                                                SWIG_CSharpExceptionCallback_t divideByZeroCallback, 
                                                SWIG_CSharpExceptionCallback_t indexOutOfRangeCallback, 
                                                SWIG_CSharpExceptionCallback_t invalidCastCallback,
                                                SWIG_CSharpExceptionCallback_t invalidOperationCallback,
                                                SWIG_CSharpExceptionCallback_t ioCallback,
                                                SWIG_CSharpExceptionCallback_t nullReferenceCallback,
                                                SWIG_CSharpExceptionCallback_t outOfMemoryCallback, 
                                                SWIG_CSharpExceptionCallback_t overflowCallback, 
                                                SWIG_CSharpExceptionCallback_t systemCallback) {
  SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback = applicationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpArithmeticException].callback = arithmeticCallback;
  SWIG_csharp_exceptions[SWIG_CSharpDivideByZeroException].callback = divideByZeroCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIndexOutOfRangeException].callback = indexOutOfRangeCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidCastException].callback = invalidCastCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidOperationException].callback = invalidOperationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIOException].callback = ioCallback;
  SWIG_csharp_exceptions[SWIG_CSharpNullReferenceException].callback = nullReferenceCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOutOfMemoryException].callback = outOfMemoryCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOverflowException].callback = overflowCallback;
  SWIG_csharp_exceptions[SWIG_CSharpSystemException].callback = systemCallback;
}

#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionArgumentCallbacks_DodoeRuntime(
                                                SWIG_CSharpExceptionArgumentCallback_t argumentCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentNullCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentOutOfRangeCallback) {
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback = argumentCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentNullException].callback = argumentNullCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentOutOfRangeException].callback = argumentOutOfRangeCallback;
}


/* Callback for returning strings to C# without leaking memory */
typedef char * (SWIGSTDCALL* SWIG_CSharpStringHelperCallback)(const char *);
static SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL;


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterStringCallback_DodoeRuntime(SWIG_CSharpStringHelperCallback callback) {
  SWIG_csharp_string_callback = callback;
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) do { if (!(expr)) {SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, msg, ""); return nullreturn; } } while (0)


#ifdef __cplusplus
#include <utility>
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigSmartPointer {
    T *ptr;
    SwigSmartPointer(T *p) : ptr(p) { }
    ~SwigSmartPointer() { delete ptr; }
    SwigSmartPointer& operator=(SwigSmartPointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
    void reset(T *p) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = p; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigSmartPointer tmp(new T(t)); pointer = tmp; return *this; }
#if __cplusplus >=201103L
  SwigValueWrapper& operator=(T&& t) { SwigSmartPointer tmp(new T(std::move(t))); pointer = tmp; return *this; }
  operator T&&() const { return std::move(*pointer.ptr); }
#else
  operator T&() const { return *pointer.ptr; }
#endif
  T *operator&() const { return pointer.ptr; }
  static void reset(SwigValueWrapper& t, T *p) { t.pointer.reset(p); }
};

/*
 * SwigValueInit() is a generic initialisation solution as the following approach:
 * 
 *       T c_result = T();
 * 
 * doesn't compile for all types for example:
 * 
 *       unsigned int c_result = unsigned int();
 */
template <typename T> T SwigValueInit() {
  return T();
}

#if __cplusplus >=201103L
# define SWIG_STD_MOVE(OBJ) std::move(OBJ)
#else
# define SWIG_STD_MOVE(OBJ) OBJ
#endif

#endif

#if defined(__cplusplus) && (__cplusplus >=201103L)
# define SWIG_OVERRIDE override
#else
# define SWIG_OVERRIDE
#endif



#include <stdint.h>		// Use the C99 official header


#include "native_api/dodoe_api.h"


#include <string.h>


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void SWIGSTDCALL CSharp_DodoefBindings_DodoeVec2_x_set___(void * jarg1, float jarg2) {
  DodoeVec2 *arg1 = 0 ;
  float arg2 ;
  
  arg1 = (DodoeVec2 *)jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->x = arg2;
}


SWIGEXPORT float SWIGSTDCALL CSharp_DodoefBindings_DodoeVec2_x_get___(void * jarg1) {
  float jresult ;
  DodoeVec2 *arg1 = 0 ;
  float result;
  
  arg1 = (DodoeVec2 *)jarg1; 
  result = (float) ((arg1)->x);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DodoefBindings_DodoeVec2_y_set___(void * jarg1, float jarg2) {
  DodoeVec2 *arg1 = 0 ;
  float arg2 ;
  
  arg1 = (DodoeVec2 *)jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->y = arg2;
}


SWIGEXPORT float SWIGSTDCALL CSharp_DodoefBindings_DodoeVec2_y_get___(void * jarg1) {
  float jresult ;
  DodoeVec2 *arg1 = 0 ;
  float result;
  
  arg1 = (DodoeVec2 *)jarg1; 
  result = (float) ((arg1)->y);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DodoefBindings_new_DodoeVec2___() {
  void * jresult ;
  DodoeVec2 *result = 0 ;
  
  result = (DodoeVec2 *)new DodoeVec2();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DodoefBindings_delete_DodoeVec2___(void * jarg1) {
  DodoeVec2 *arg1 = 0 ;
  
  arg1 = (DodoeVec2 *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DodoefBindings_DodoeVec3_x_set___(void * jarg1, float jarg2) {
  DodoeVec3 *arg1 = 0 ;
  float arg2 ;
  
  arg1 = (DodoeVec3 *)jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->x = arg2;
}


SWIGEXPORT float SWIGSTDCALL CSharp_DodoefBindings_DodoeVec3_x_get___(void * jarg1) {
  float jresult ;
  DodoeVec3 *arg1 = 0 ;
  float result;
  
  arg1 = (DodoeVec3 *)jarg1; 
  result = (float) ((arg1)->x);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DodoefBindings_DodoeVec3_y_set___(void * jarg1, float jarg2) {
  DodoeVec3 *arg1 = 0 ;
  float arg2 ;
  
  arg1 = (DodoeVec3 *)jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->y = arg2;
}


SWIGEXPORT float SWIGSTDCALL CSharp_DodoefBindings_DodoeVec3_y_get___(void * jarg1) {
  float jresult ;
  DodoeVec3 *arg1 = 0 ;
  float result;
  
  arg1 = (DodoeVec3 *)jarg1; 
  result = (float) ((arg1)->y);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DodoefBindings_DodoeVec3_z_set___(void * jarg1, float jarg2) {
  DodoeVec3 *arg1 = 0 ;
  float arg2 ;
  
  arg1 = (DodoeVec3 *)jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->z = arg2;
}


SWIGEXPORT float SWIGSTDCALL CSharp_DodoefBindings_DodoeVec3_z_get___(void * jarg1) {
  float jresult ;
  DodoeVec3 *arg1 = 0 ;
  float result;
  
  arg1 = (DodoeVec3 *)jarg1; 
  result = (float) ((arg1)->z);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DodoefBindings_new_DodoeVec3___() {
  void * jresult ;
  DodoeVec3 *result = 0 ;
  
  result = (DodoeVec3 *)new DodoeVec3();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DodoefBindings_delete_DodoeVec3___(void * jarg1) {
  DodoeVec3 *arg1 = 0 ;
  
  arg1 = (DodoeVec3 *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DodoefBindings_DodoeColor_r_set___(void * jarg1, float jarg2) {
  DodoeColor *arg1 = 0 ;
  float arg2 ;
  
  arg1 = (DodoeColor *)jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->r = arg2;
}


SWIGEXPORT float SWIGSTDCALL CSharp_DodoefBindings_DodoeColor_r_get___(void * jarg1) {
  float jresult ;
  DodoeColor *arg1 = 0 ;
  float result;
  
  arg1 = (DodoeColor *)jarg1; 
  result = (float) ((arg1)->r);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DodoefBindings_DodoeColor_g_set___(void * jarg1, float jarg2) {
  DodoeColor *arg1 = 0 ;
  float arg2 ;
  
  arg1 = (DodoeColor *)jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->g = arg2;
}


SWIGEXPORT float SWIGSTDCALL CSharp_DodoefBindings_DodoeColor_g_get___(void * jarg1) {
  float jresult ;
  DodoeColor *arg1 = 0 ;
  float result;
  
  arg1 = (DodoeColor *)jarg1; 
  result = (float) ((arg1)->g);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DodoefBindings_DodoeColor_b_set___(void * jarg1, float jarg2) {
  DodoeColor *arg1 = 0 ;
  float arg2 ;
  
  arg1 = (DodoeColor *)jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->b = arg2;
}


SWIGEXPORT float SWIGSTDCALL CSharp_DodoefBindings_DodoeColor_b_get___(void * jarg1) {
  float jresult ;
  DodoeColor *arg1 = 0 ;
  float result;
  
  arg1 = (DodoeColor *)jarg1; 
  result = (float) ((arg1)->b);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DodoefBindings_DodoeColor_a_set___(void * jarg1, float jarg2) {
  DodoeColor *arg1 = 0 ;
  float arg2 ;
  
  arg1 = (DodoeColor *)jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->a = arg2;
}


SWIGEXPORT float SWIGSTDCALL CSharp_DodoefBindings_DodoeColor_a_get___(void * jarg1) {
  float jresult ;
  DodoeColor *arg1 = 0 ;
  float result;
  
  arg1 = (DodoeColor *)jarg1; 
  result = (float) ((arg1)->a);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DodoefBindings_new_DodoeColor___() {
  void * jresult ;
  DodoeColor *result = 0 ;
  
  result = (DodoeColor *)new DodoeColor();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DodoefBindings_delete_DodoeColor___(void * jarg1) {
  DodoeColor *arg1 = 0 ;
  
  arg1 = (DodoeColor *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DodoefBindings_DodoeAssetRef_id_set___(void * jarg1, unsigned long long jarg2) {
  DodoeAssetRef *arg1 = 0 ;
  DodoeAssetId arg2 ;
  
  arg1 = (DodoeAssetRef *)jarg1; 
  arg2 = (DodoeAssetId)jarg2; 
  if (arg1) (arg1)->id = arg2;
}


SWIGEXPORT unsigned long long SWIGSTDCALL CSharp_DodoefBindings_DodoeAssetRef_id_get___(void * jarg1) {
  unsigned long long jresult ;
  DodoeAssetRef *arg1 = 0 ;
  DodoeAssetId result;
  
  arg1 = (DodoeAssetRef *)jarg1; 
  result = (DodoeAssetId) ((arg1)->id);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DodoefBindings_DodoeAssetRef_path_id_set___(void * jarg1, unsigned long long jarg2) {
  DodoeAssetRef *arg1 = 0 ;
  DodoeTextureId arg2 ;
  
  arg1 = (DodoeAssetRef *)jarg1; 
  arg2 = (DodoeTextureId)jarg2; 
  if (arg1) (arg1)->path_id = arg2;
}


SWIGEXPORT unsigned long long SWIGSTDCALL CSharp_DodoefBindings_DodoeAssetRef_path_id_get___(void * jarg1) {
  unsigned long long jresult ;
  DodoeAssetRef *arg1 = 0 ;
  DodoeTextureId result;
  
  arg1 = (DodoeAssetRef *)jarg1; 
  result = (DodoeTextureId) ((arg1)->path_id);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DodoefBindings_DodoeAssetRef_path_set___(void * jarg1, char * jarg2) {
  DodoeAssetRef *arg1 = 0 ;
  char *arg2 = 0 ;
  
  arg1 = (DodoeAssetRef *)jarg1; 
  arg2 = (char *)jarg2; 
  {
    if (arg2) {
      arg1->path = (char const *) (new char[strlen((const char *)arg2)+1]);
      strcpy((char *)arg1->path, (const char *)arg2);
    } else {
      arg1->path = 0;
    }
  }
}


SWIGEXPORT char * SWIGSTDCALL CSharp_DodoefBindings_DodoeAssetRef_path_get___(void * jarg1) {
  char * jresult ;
  DodoeAssetRef *arg1 = 0 ;
  char *result = 0 ;
  
  arg1 = (DodoeAssetRef *)jarg1; 
  result = (char *) ((arg1)->path);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DodoefBindings_DodoeAssetRef_type_set___(void * jarg1, char * jarg2) {
  DodoeAssetRef *arg1 = 0 ;
  char *arg2 = 0 ;
  
  arg1 = (DodoeAssetRef *)jarg1; 
  arg2 = (char *)jarg2; 
  {
    if (arg2) {
      arg1->type = (char const *) (new char[strlen((const char *)arg2)+1]);
      strcpy((char *)arg1->type, (const char *)arg2);
    } else {
      arg1->type = 0;
    }
  }
}


SWIGEXPORT char * SWIGSTDCALL CSharp_DodoefBindings_DodoeAssetRef_type_get___(void * jarg1) {
  char * jresult ;
  DodoeAssetRef *arg1 = 0 ;
  char *result = 0 ;
  
  arg1 = (DodoeAssetRef *)jarg1; 
  result = (char *) ((arg1)->type);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DodoefBindings_new_DodoeAssetRef___() {
  void * jresult ;
  DodoeAssetRef *result = 0 ;
  
  result = (DodoeAssetRef *)new DodoeAssetRef();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DodoefBindings_delete_DodoeAssetRef___(void * jarg1) {
  DodoeAssetRef *arg1 = 0 ;
  
  arg1 = (DodoeAssetRef *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DodoefBindings_DodoeTextureInfo_id_set___(void * jarg1, unsigned long long jarg2) {
  DodoeTextureInfo *arg1 = 0 ;
  DodoeTextureId arg2 ;
  
  arg1 = (DodoeTextureInfo *)jarg1; 
  arg2 = (DodoeTextureId)jarg2; 
  if (arg1) (arg1)->id = arg2;
}


SWIGEXPORT unsigned long long SWIGSTDCALL CSharp_DodoefBindings_DodoeTextureInfo_id_get___(void * jarg1) {
  unsigned long long jresult ;
  DodoeTextureInfo *arg1 = 0 ;
  DodoeTextureId result;
  
  arg1 = (DodoeTextureInfo *)jarg1; 
  result = (DodoeTextureId) ((arg1)->id);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DodoefBindings_DodoeTextureInfo_path_set___(void * jarg1, char * jarg2) {
  DodoeTextureInfo *arg1 = 0 ;
  char *arg2 = 0 ;
  
  arg1 = (DodoeTextureInfo *)jarg1; 
  arg2 = (char *)jarg2; 
  {
    if (arg2) {
      arg1->path = (char const *) (new char[strlen((const char *)arg2)+1]);
      strcpy((char *)arg1->path, (const char *)arg2);
    } else {
      arg1->path = 0;
    }
  }
}


SWIGEXPORT char * SWIGSTDCALL CSharp_DodoefBindings_DodoeTextureInfo_path_get___(void * jarg1) {
  char * jresult ;
  DodoeTextureInfo *arg1 = 0 ;
  char *result = 0 ;
  
  arg1 = (DodoeTextureInfo *)jarg1; 
  result = (char *) ((arg1)->path);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DodoefBindings_DodoeTextureInfo_width_set___(void * jarg1, int jarg2) {
  DodoeTextureInfo *arg1 = 0 ;
  int arg2 ;
  
  arg1 = (DodoeTextureInfo *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->width = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_DodoefBindings_DodoeTextureInfo_width_get___(void * jarg1) {
  int jresult ;
  DodoeTextureInfo *arg1 = 0 ;
  int result;
  
  arg1 = (DodoeTextureInfo *)jarg1; 
  result = (int) ((arg1)->width);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DodoefBindings_DodoeTextureInfo_height_set___(void * jarg1, int jarg2) {
  DodoeTextureInfo *arg1 = 0 ;
  int arg2 ;
  
  arg1 = (DodoeTextureInfo *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->height = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_DodoefBindings_DodoeTextureInfo_height_get___(void * jarg1) {
  int jresult ;
  DodoeTextureInfo *arg1 = 0 ;
  int result;
  
  arg1 = (DodoeTextureInfo *)jarg1; 
  result = (int) ((arg1)->height);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DodoefBindings_new_DodoeTextureInfo___() {
  void * jresult ;
  DodoeTextureInfo *result = 0 ;
  
  result = (DodoeTextureInfo *)new DodoeTextureInfo();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DodoefBindings_delete_DodoeTextureInfo___(void * jarg1) {
  DodoeTextureInfo *arg1 = 0 ;
  
  arg1 = (DodoeTextureInfo *)jarg1; 
  delete arg1;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DodoefBindings_dodoe_context_create___() {
  void * jresult ;
  void *result = 0 ;
  
  result = (void *)dodoe_context_create();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DodoefBindings_dodoe_context_destroy___(void * jarg1) {
  void *arg1 = 0 ;
  
  arg1 = (void *)jarg1; 
  dodoe_context_destroy(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DodoefBindings_dodoe_context_tick___(void * jarg1) {
  void *arg1 = 0 ;
  
  arg1 = (void *)jarg1; 
  dodoe_context_tick(arg1);
}


SWIGEXPORT char * SWIGSTDCALL CSharp_DodoefBindings_dodoe_get_version___() {
  char * jresult ;
  char *result = 0 ;
  
  result = (char *)dodoe_get_version();
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DodoefBindings_dodoe_get_native_window___(void * jarg1) {
  void * jresult ;
  void *arg1 = 0 ;
  void *result = 0 ;
  
  arg1 = (void *)jarg1; 
  result = (void *)dodoe_get_native_window(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DodoefBindings_dodoe_show_window___(void * jarg1, unsigned int jarg2) {
  void *arg1 = 0 ;
  bool arg2 ;
  
  arg1 = (void *)jarg1; 
  arg2 = jarg2 ? true : false; 
  dodoe_show_window(arg1,arg2);
}


SWIGEXPORT unsigned long long SWIGSTDCALL CSharp_DodoefBindings_dodoe_entity_create___(void * jarg1) {
  unsigned long long jresult ;
  void *arg1 = 0 ;
  DodoeHandle result;
  
  arg1 = (void *)jarg1; 
  result = (DodoeHandle)dodoe_entity_create(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DodoefBindings_dodoe_entity_destroy___(void * jarg1, unsigned long long jarg2) {
  void *arg1 = 0 ;
  DodoeHandle arg2 ;
  
  arg1 = (void *)jarg1; 
  arg2 = (DodoeHandle)jarg2; 
  dodoe_entity_destroy(arg1,arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DodoefBindings_dodoe_entity_set_name___(void * jarg1, unsigned long long jarg2, char * jarg3) {
  void *arg1 = 0 ;
  DodoeHandle arg2 ;
  char *arg3 = 0 ;
  
  arg1 = (void *)jarg1; 
  arg2 = (DodoeHandle)jarg2; 
  arg3 = (char *)jarg3; 
  dodoe_entity_set_name(arg1,arg2,(char const *)arg3);
}


SWIGEXPORT char * SWIGSTDCALL CSharp_DodoefBindings_dodoe_entity_get_name___(void * jarg1, unsigned long long jarg2) {
  char * jresult ;
  void *arg1 = 0 ;
  DodoeHandle arg2 ;
  char *result = 0 ;
  
  arg1 = (void *)jarg1; 
  arg2 = (DodoeHandle)jarg2; 
  result = (char *)dodoe_entity_get_name(arg1,arg2);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DodoefBindings_dodoe_entity_set_position___(void * jarg1, unsigned long long jarg2, void * jarg3) {
  void *arg1 = 0 ;
  DodoeHandle arg2 ;
  DodoeVec2 arg3 ;
  DodoeVec2 *argp3 ;
  
  arg1 = (void *)jarg1; 
  arg2 = (DodoeHandle)jarg2; 
  argp3 = (DodoeVec2 *)jarg3; 
  if (!argp3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null DodoeVec2", 0);
    return ;
  }
  arg3 = *argp3; 
  dodoe_entity_set_position(arg1,arg2,SWIG_STD_MOVE(arg3));
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DodoefBindings_dodoe_entity_get_position___(void * jarg1, unsigned long long jarg2) {
  void * jresult ;
  void *arg1 = 0 ;
  DodoeHandle arg2 ;
  DodoeVec2 result;
  
  arg1 = (void *)jarg1; 
  arg2 = (DodoeHandle)jarg2; 
  result = dodoe_entity_get_position(arg1,arg2);
  jresult = new DodoeVec2(result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DodoefBindings_dodoe_entity_set_scale___(void * jarg1, unsigned long long jarg2, void * jarg3) {
  void *arg1 = 0 ;
  DodoeHandle arg2 ;
  DodoeVec2 arg3 ;
  DodoeVec2 *argp3 ;
  
  arg1 = (void *)jarg1; 
  arg2 = (DodoeHandle)jarg2; 
  argp3 = (DodoeVec2 *)jarg3; 
  if (!argp3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null DodoeVec2", 0);
    return ;
  }
  arg3 = *argp3; 
  dodoe_entity_set_scale(arg1,arg2,SWIG_STD_MOVE(arg3));
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DodoefBindings_dodoe_entity_get_scale___(void * jarg1, unsigned long long jarg2) {
  void * jresult ;
  void *arg1 = 0 ;
  DodoeHandle arg2 ;
  DodoeVec2 result;
  
  arg1 = (void *)jarg1; 
  arg2 = (DodoeHandle)jarg2; 
  result = dodoe_entity_get_scale(arg1,arg2);
  jresult = new DodoeVec2(result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DodoefBindings_dodoe_entity_set_rotation___(void * jarg1, unsigned long long jarg2, float jarg3) {
  void *arg1 = 0 ;
  DodoeHandle arg2 ;
  float arg3 ;
  
  arg1 = (void *)jarg1; 
  arg2 = (DodoeHandle)jarg2; 
  arg3 = (float)jarg3; 
  dodoe_entity_set_rotation(arg1,arg2,arg3);
}


SWIGEXPORT float SWIGSTDCALL CSharp_DodoefBindings_dodoe_entity_get_rotation___(void * jarg1, unsigned long long jarg2) {
  float jresult ;
  void *arg1 = 0 ;
  DodoeHandle arg2 ;
  float result;
  
  arg1 = (void *)jarg1; 
  arg2 = (DodoeHandle)jarg2; 
  result = (float)dodoe_entity_get_rotation(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_DodoefBindings_dodoe_entity_get_child_count___(void * jarg1, unsigned long long jarg2) {
  int jresult ;
  void *arg1 = 0 ;
  DodoeHandle arg2 ;
  int result;
  
  arg1 = (void *)jarg1; 
  arg2 = (DodoeHandle)jarg2; 
  result = (int)dodoe_entity_get_child_count(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned long long SWIGSTDCALL CSharp_DodoefBindings_dodoe_entity_get_child_at___(void * jarg1, unsigned long long jarg2, int jarg3) {
  unsigned long long jresult ;
  void *arg1 = 0 ;
  DodoeHandle arg2 ;
  int arg3 ;
  DodoeHandle result;
  
  arg1 = (void *)jarg1; 
  arg2 = (DodoeHandle)jarg2; 
  arg3 = (int)jarg3; 
  result = (DodoeHandle)dodoe_entity_get_child_at(arg1,arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DodoefBindings_dodoe_entity_set_parent___(void * jarg1, unsigned long long jarg2, unsigned long long jarg3) {
  void *arg1 = 0 ;
  DodoeHandle arg2 ;
  DodoeHandle arg3 ;
  
  arg1 = (void *)jarg1; 
  arg2 = (DodoeHandle)jarg2; 
  arg3 = (DodoeHandle)jarg3; 
  dodoe_entity_set_parent(arg1,arg2,arg3);
}


SWIGEXPORT int SWIGSTDCALL CSharp_DodoefBindings_dodoe_entity_has_component___(void * jarg1, unsigned long long jarg2, char * jarg3) {
  int jresult ;
  void *arg1 = 0 ;
  DodoeHandle arg2 ;
  char *arg3 = 0 ;
  int result;
  
  arg1 = (void *)jarg1; 
  arg2 = (DodoeHandle)jarg2; 
  arg3 = (char *)jarg3; 
  result = (int)dodoe_entity_has_component(arg1,arg2,(char const *)arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DodoefBindings_dodoe_entity_add_component___(void * jarg1, unsigned long long jarg2, char * jarg3) {
  void *arg1 = 0 ;
  DodoeHandle arg2 ;
  char *arg3 = 0 ;
  
  arg1 = (void *)jarg1; 
  arg2 = (DodoeHandle)jarg2; 
  arg3 = (char *)jarg3; 
  dodoe_entity_add_component(arg1,arg2,(char const *)arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DodoefBindings_dodoe_entity_remove_component___(void * jarg1, unsigned long long jarg2, char * jarg3) {
  void *arg1 = 0 ;
  DodoeHandle arg2 ;
  char *arg3 = 0 ;
  
  arg1 = (void *)jarg1; 
  arg2 = (DodoeHandle)jarg2; 
  arg3 = (char *)jarg3; 
  dodoe_entity_remove_component(arg1,arg2,(char const *)arg3);
}


SWIGEXPORT int SWIGSTDCALL CSharp_DodoefBindings_dodoe_entity_get_component_count___(void * jarg1, unsigned long long jarg2) {
  int jresult ;
  void *arg1 = 0 ;
  DodoeHandle arg2 ;
  int result;
  
  arg1 = (void *)jarg1; 
  arg2 = (DodoeHandle)jarg2; 
  result = (int)dodoe_entity_get_component_count(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_DodoefBindings_dodoe_entity_get_component_type___(void * jarg1, unsigned long long jarg2, int jarg3) {
  char * jresult ;
  void *arg1 = 0 ;
  DodoeHandle arg2 ;
  int arg3 ;
  char *result = 0 ;
  
  arg1 = (void *)jarg1; 
  arg2 = (DodoeHandle)jarg2; 
  arg3 = (int)jarg3; 
  result = (char *)dodoe_entity_get_component_type(arg1,arg2,arg3);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT unsigned long long SWIGSTDCALL CSharp_DodoefBindings_dodoe_texture_load___(void * jarg1, char * jarg2) {
  unsigned long long jresult ;
  void *arg1 = 0 ;
  char *arg2 = 0 ;
  DodoeTextureId result;
  
  arg1 = (void *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (DodoeTextureId)dodoe_texture_load(arg1,(char const *)arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DodoefBindings_dodoe_texture_get_info___(void * jarg1, unsigned long long jarg2) {
  void * jresult ;
  void *arg1 = 0 ;
  DodoeTextureId arg2 ;
  DodoeTextureInfo result;
  
  arg1 = (void *)jarg1; 
  arg2 = (DodoeTextureId)jarg2; 
  result = dodoe_texture_get_info(arg1,arg2);
  jresult = new DodoeTextureInfo(result); 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_DodoefBindings_dodoe_texture_get_loaded_count___(void * jarg1) {
  int jresult ;
  void *arg1 = 0 ;
  int result;
  
  arg1 = (void *)jarg1; 
  result = (int)dodoe_texture_get_loaded_count(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_DodoefBindings_dodoe_asset_get_count___(void * jarg1, char * jarg2) {
  int jresult ;
  void *arg1 = 0 ;
  char *arg2 = 0 ;
  int result;
  
  arg1 = (void *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (int)dodoe_asset_get_count(arg1,(char const *)arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_DodoefBindings_dodoe_asset_get_at___(void * jarg1, char * jarg2, int jarg3) {
  void * jresult ;
  void *arg1 = 0 ;
  char *arg2 = 0 ;
  int arg3 ;
  DodoeAssetRef result;
  
  arg1 = (void *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (int)jarg3; 
  result = dodoe_asset_get_at(arg1,(char const *)arg2,arg3);
  jresult = new DodoeAssetRef(result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DodoefBindings_dodoe_editor_select_entity___(void * jarg1, unsigned long long jarg2) {
  void *arg1 = 0 ;
  DodoeHandle arg2 ;
  
  arg1 = (void *)jarg1; 
  arg2 = (DodoeHandle)jarg2; 
  dodoe_editor_select_entity(arg1,arg2);
}


SWIGEXPORT unsigned long long SWIGSTDCALL CSharp_DodoefBindings_dodoe_editor_get_selected_entity___(void * jarg1) {
  unsigned long long jresult ;
  void *arg1 = 0 ;
  DodoeHandle result;
  
  arg1 = (void *)jarg1; 
  result = (DodoeHandle)dodoe_editor_get_selected_entity(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_DodoefBindings_dodoe_world_set_state___(void * jarg1, int jarg2) {
  void *arg1 = 0 ;
  int arg2 ;
  
  arg1 = (void *)jarg1; 
  arg2 = (int)jarg2; 
  dodoe_world_set_state(arg1,arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DodoefBindings_dodoe_viewport_attach___(void * jarg1, void * jarg2, int jarg3, int jarg4) {
  void *arg1 = 0 ;
  void *arg2 = 0 ;
  int arg3 ;
  int arg4 ;
  
  arg1 = (void *)jarg1; 
  arg2 = (void *)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  dodoe_viewport_attach(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DodoefBindings_dodoe_viewport_resize___(void * jarg1, int jarg2, int jarg3) {
  void *arg1 = 0 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = (void *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  dodoe_viewport_resize(arg1,arg2,arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_DodoefBindings_dodoe_viewport_detach___(void * jarg1) {
  void *arg1 = 0 ;
  
  arg1 = (void *)jarg1; 
  dodoe_viewport_detach(arg1);
}


#ifdef __cplusplus
}
#endif

