// do@Redlive

#pragma once

#include <iostream>
#include <memory>
#include <utility>
#include <algorithm>
#include <functional>
#include <filesystem>
#include <mutex>
#include <optional>
#include <string>
#include <string_view>
#include <sstream>
#include <fstream>
#include <array>
#include <vector>
#include <queue>
#include <deque>
#include <unordered_map>
#include <unordered_set>

#include <type_traits>
#include <bit>

#include "runtime/core/core.h"
#include "runtime/core/base.h"
#include "runtime/core/container/containers.h"
#include "runtime/core/asserts.h"
#include "runtime/core/debug/instrumentor.h"
#include "runtime/core/memory/managed.h"
#include "runtime/function/log/log_system.h"

using dodoe::Bool;
using dodoe::Byte;
using dodoe::Char;
using dodoe::Float;
using dodoe::Int;
using dodoe::UInt;
using dodoe::Size_t;
using dodoe::Int8;
using dodoe::Int16;
using dodoe::Int32;
using dodoe::Int64;
using dodoe::UInt8;
using dodoe::UInt16;
using dodoe::UInt32;
using dodoe::UInt64;
using dodoe::String;
using dodoe::StringView;
using dodoe::DynamicArray;
using dodoe::Vector2f;
using dodoe::Vector2i;
using dodoe::Vector3f;
using dodoe::Vector3i;
using dodoe::Vector4f;
using dodoe::Vector4i;
using dodoe::Matrix3f;
using dodoe::Matrix4f;
