//
// Generated by AI;
//

#ifndef DODOE_SANDBOX_LAYER_H
#define DODOE_SANDBOX_LAYER_H

#include "dopch.h"
#include "runtime/core/layer/layer.h"

namespace sandbox {

    class SandboxLayer : public dodoe::Layer {
    public:
        explicit SandboxLayer(const std::string& name);
        ~SandboxLayer() override = default;

        void attach() override;
        void detach() override;
        void updateTick(float delta_time) override;
        void renderTick() override;
    };

} // namespace sandbox

#endif // DODOE_SANDBOX_LAYER_H
